# Generated by Django 3.2.6 on 2021-08-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='TAG')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='REG Time')),
            ],
            options={
                'verbose_name': 'TAG',
                'verbose_name_plural': 'TAG',
                'db_table': 'fastcampus_tag',
            },
        ),
    ]
