# Generated by Django 3.2.6 on 2021-08-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': 'NamoWebiz 사용자', 'verbose_name_plural': 'NamoWebiz 사용자'},
        ),
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(default='test@test.com', max_length=128, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fcuser',
            name='password',
            field=models.CharField(max_length=64, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='fcuser',
            name='registered_dttm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='REG Time'),
        ),
        migrations.AlterField(
            model_name='fcuser',
            name='username',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
    ]
